# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y6MzjuECey4h7HhCjCYjdd1ePZVOplTa
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x=np.linspace(0,1,100)
y=np.linspace(2,3,100)
plt.plot(x,y)

plt.savefig("trialfile.png")

